#!/usr/bin/env python3
# SPDX-License-Identifier: Unlicense
"""Build one agent-friendly Markdown file from the Omarchy manual chapters."""

from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path, PurePosixPath


HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$", re.MULTILINE)
IMAGE_LINE_RE = re.compile(
    r"^[ \t]*!\[[^\]]*\]\([^\n)]*\)[ \t]*$", re.MULTILINE
)
IMAGE_RE = re.compile(r"!\[[^\]]*\]\(")
MARKDOWN_LINK_RE = re.compile(
    r"(?<!!)\[([^\]]+)\]\(([^()\s]+(?:#[^()\s]*)?)\)"
)
RELATIVE_MARKDOWN_LINK_RE = re.compile(
    r"(?<!!)\[[^\]]+\]\((?![a-z][a-z0-9+.-]*:|#)[^()\s]*\.md(?:#[^()\s]*)?\)",
    re.IGNORECASE,
)

GENERATED_HEADER = """<!--
This file is generated by scripts/build-manual.py from the Omarchy manual.
Do not edit it directly.
-->
"""


class BuildError(Exception):
    """Raised when the source manual cannot be combined safely."""


def github_slug(value: str) -> str:
    """Return the GitHub-style anchor slug needed by source fragment links."""
    value = re.sub(r"<[^>]+>", "", value).strip().lower()
    value = "".join(
        character
        for character in value
        if character in "-_"
        or character.isspace()
        or not unicodedata.category(character).startswith(("P", "S"))
    )
    return re.sub(r"\s", "-", value)


def heading_fragments(markdown: str) -> dict[str, re.Match[str]]:
    """Map GitHub heading fragments to their heading matches within one chapter."""
    matches: dict[str, re.Match[str]] = {}
    occurrences: defaultdict[str, int] = defaultdict(int)

    for match in HEADING_RE.finditer(markdown):
        base = github_slug(match.group(2))
        duplicate_number = occurrences[base]
        occurrences[base] += 1
        fragment = base if duplicate_number == 0 else f"{base}-{duplicate_number}"
        matches[fragment] = match

    return matches


def split_destination(destination: str) -> tuple[str, str | None]:
    path, separator, fragment = destination.partition("#")
    return path, fragment if separator else None


def local_chapter_name(path: str) -> str | None:
    if re.match(r"^[a-z][a-z0-9+.-]*:", path, re.IGNORECASE) or path.startswith("/"):
        return None

    normalized = str(PurePosixPath(path))
    if normalized.startswith("../") or PurePosixPath(normalized).suffix.lower() != ".md":
        return None

    return normalized.removeprefix("./")


def collect_link_targets(
    chapters: dict[str, str],
) -> dict[str, set[str]]:
    required_fragments: defaultdict[str, set[str]] = defaultdict(set)

    for source_name, markdown in chapters.items():
        for match in MARKDOWN_LINK_RE.finditer(markdown):
            path, fragment = split_destination(match.group(2))
            target_name = local_chapter_name(path)
            if target_name is None:
                continue
            if target_name not in chapters:
                raise BuildError(
                    f"{source_name}: link target does not exist: {match.group(2)}"
                )
            if fragment:
                required_fragments[target_name].add(fragment)

    return required_fragments


def add_explicit_anchors(
    name: str, markdown: str, required_fragments: set[str]
) -> str:
    chapter_id = f"chapter-{Path(name).stem}"
    fragments = heading_fragments(markdown)
    missing = sorted(required_fragments - fragments.keys())
    if missing:
        raise BuildError(
            f"{name}: linked heading fragment(s) not found: {', '.join(missing)}"
        )

    aliases = {
        match.start(): f'<a id="{chapter_id}--{fragment}"></a>\n'
        for fragment, match in fragments.items()
        if fragment in required_fragments
    }

    pieces: list[str] = [f'<a id="{chapter_id}"></a>\n']
    position = 0
    for offset in sorted(aliases):
        pieces.append(markdown[position:offset])
        pieces.append(aliases[offset])
        position = offset
    pieces.append(markdown[position:])
    return "".join(pieces)


def rewrite_links(markdown: str, chapter_names: set[str]) -> str:
    def replacement(match: re.Match[str]) -> str:
        label, destination = match.groups()
        path, fragment = split_destination(destination)
        target_name = local_chapter_name(path)
        if target_name is None:
            return match.group(0)
        if target_name not in chapter_names:
            raise BuildError(f"link target does not exist: {destination}")

        target = f"#chapter-{Path(target_name).stem}"
        if fragment:
            target = f"{target}--{fragment}"
        return f"[{label}]({target})"

    return MARKDOWN_LINK_RE.sub(replacement, markdown)


def strip_images(markdown: str, source_name: str) -> str:
    markdown = IMAGE_LINE_RE.sub("", markdown)
    if IMAGE_RE.search(markdown):
        raise BuildError(
            f"{source_name}: unsupported inline or multiline image; "
            "move it to its own line or update the builder"
        )
    return markdown


def build(source_directory: Path) -> str:
    chapter_paths = sorted(source_directory.glob("*.md"))
    if not chapter_paths:
        raise BuildError(f"no Markdown chapters found in {source_directory}")

    chapters = {path.name: path.read_text(encoding="utf-8") for path in chapter_paths}
    required_fragments = collect_link_targets(chapters)
    chapter_names = set(chapters)
    rendered_chapters: list[str] = []

    for name, markdown in chapters.items():
        markdown = strip_images(markdown, name)
        markdown = add_explicit_anchors(name, markdown, required_fragments[name])
        markdown = rewrite_links(markdown, chapter_names)
        rendered_chapters.append(markdown.strip())

    output = GENERATED_HEADER + "\n" + "\n\n".join(rendered_chapters) + "\n"

    if IMAGE_RE.search(output):
        raise BuildError("generated manual still contains image references")
    if RELATIVE_MARKDOWN_LINK_RE.search(output):
        raise BuildError("generated manual still contains relative Markdown links")

    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="manual directory")
    parser.add_argument("--output", type=Path, required=True, help="output Markdown file")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        output = build(args.source)
        args.output.write_text(output, encoding="utf-8")
    except (BuildError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
